<link rel="icon" href="favicon.ico" type="image/x-icon">
<link rel="icon" href="Byzantine.png" type="image/png">
theme: jekyll-theme-cayman
title: Cristian Vega
description: Postdoctoral Researcher in Optimization
